artistic_styles = [
    "abstract",
    "art deco",
    "art nouveau",
    "automatism",
    "baroque",
    "classical",
    "cloisonnism",
    "constructivist",
    "contemporary",
    "cubist",
    "dada",
    "divisionism",
    "expressionist",
    "fauvist",
    "futurist",
    "geometric",
    "gothic",
    "graffiti",
    "hyperrealism",
    "impressionist",
    "lyric abstraction",
    "mannerism",
    "metaphysical",
    "minimalist",
    "naive",
    "naturalism",
    "neo-expressionism",
    "neo-impressionism",
    "neoclassical",
    "neoplasticism",
    "op art",
    "orphism",
    "photomontage",
    "photorealistic",
    "pixel art",
    "pointillist",
    "pop",
    "pop art",
    "post-impressionism",
    "precisionism",
    "primitivism",
    "realist",
    "renaissance",
    "rococo",
    "romantic",
    "spectralism",
    "stippling",
    "street art",
    "stuckist",
    "suprematist",
    "surrealist",
    "symbolist",
    "tachisme",
    "transgressive",
]

color_palettes = [
    "achromatic",
    "analogous",
    "analogous colors",
    "black and white",
    "clash",
    "complementary",
    "complementary colors",
    "cool tones",
    "dark",
    "desaturated",
    "discordant",
    "duotone",
    "earth tones",
    "fauvist",
    "grayscale",
    "harmonious",
    "high contrast",
    "light",
    "low contrast",
    "matte",
    "metallic",
    "monochromatic",
    "monochrome",
    "multicolor",
    "muted",
    "natural",
    "neon",
    "neutral",
    "pastel",
    "polychromatic",
    "primary colors",
    "psychedelic",
    "rectangular",
    "retro",
    "saturated",
    "secondary colors",
    "sepia",
    "shaded",
    "solarized",
    "split-complementary",
    "square",
    "synthetic",
    "tertiary colors",
    "tetradic",
    "tetradic colors",
    "tinted",
    "toned",
    "triadic",
    "triadic colors",
    "vibrant",
    "vintage",
    "warm tones",
]

emotions = [
    "ambitious",
    "amused",
    "angry",
    "anxious",
    "apathetic",
    "assertive",
    "awkward",
    "bewildered",
    "bored",
    "brave",
    "calm",
    "comfortable",
    "compassionate",
    "confident",
    "content",
    "curious",
    "discontent",
    "distracted",
    "eager",
    "ecstatic",
    "energetic",
    "enthusiastic",
    "envious",
    "excited",
    "fearful",
    "focused",
    "forlorn",
    "grateful",
    "hateful",
    "hesitant",
    "hopeful",
    "indifferent",
    "insecure",
    "introspective",
    "joyful",
    "lazy",
    "loving",
    "melancholic",
    "mysterious",
    "optimistic",
    "peaceful",
    "pensive",
    "pessimistic",
    "reluctant",
    "secure",
    "serene",
    "timid",
]

geographical_locations = [
    "archipelago",
    "arctic",
    "canyon",
    "cave",
    "cliff",
    "coastal",
    "coral reef",
    "delta",
    "desert",
    "dune",
    "estuary",
    "farmland",
    "fjord",
    "forest",
    "garden",
    "glacier",
    "grove",
    "hill",
    "island",
    "jungle",
    "lagoon",
    "lakeside",
    "marshland",
    "meadow",
    "mountainous",
    "oceanic",
    "orchard",
    "plain",
    "plateau",
    "pond",
    "prairie",
    "ridge",
    "riverine",
    "rural",
    "savanna",
    "steppe",
    "suburban",
    "swamp",
    "taiga",
    "tropical",
    "tundra",
    "urban",
    "valley",
    "vineyard",
    "volcanic",
    "waterfall",
]

historical_references = [
    "agricultural",
    "ancient",
    "atomic age",
    # "aztec",
    "babylonian",
    "baroque",
    "bronze age",
    "byzantine",
    # "civil war",
    # "cold war",
    "colonial",
    "dark ages",
    "democratic",
    "egyptian",
    "enlightenment",
    "feudal",
    # "gothic",
    # "han dynasty",
    "hellenistic",
    "hunter-gatherer",
    "imperial",
    "incan",
    "industrial",
    "information age",
    "iron age",
    # "islamic golden age",
    # "mayan",
    "medieval",
    "modern",
    # "mughal",
    "neolithic",
    "oligarchy",
    # "ottoman",
    # "persian",
    "prehistoric",
    "renaissance",
    "republic",
    "roaring twenties",
    "roman",
    "space age",
    "sumerian",
    "theocracy",
    "tribal",
    "victorian",
    "viking",
    # "world war i",
    # "world war ii",
]

interactions = [
    "aligning",
    "amplifying",
    "balancing",
    "clashing",
    "coalescing",
    "complementing",
    "contrasting",
    "dampening",
    "diminishing",
    "disordering",
    "disrupting",
    "distorting",
    "diverging",
    "dominating",
    "encircling",
    "enhancing",
    "following",
    "fragmenting",
    "freeing",
    "fusing",
    "guiding",
    "halting",
    "highlighting",
    "illuminating",
    "inspiring",
    "interrupting",
    "intersecting",
    "merging",
    "mimicking",
    "misleading",
    "muting",
    "obscuring",
    "organizing",
    "overlapping",
    "paralleling",
    "pausing",
    "polarizing",
    "preceding",
    "reflecting",
    "revealing",
    "rushing",
    "separating",
    "shadowing",
    "submitting",
    "supporting",
    "trapping",
    "unbalancing",
    "uniting",
]

mediums = [
    "acrylic",
    "aluminum",
    "bronze",
    "ceramic",
    "chalk",
    "charcoal",
    "clay",
    "collage",
    "concrete",
    "copper",
    "coral",
    "crystal",
    "digital art",
    "enamel",
    "etching",
    "fabric",
    "fiberglass",
    "fur",
    "glass",
    "gold leaf",
    "gouache",
    "granite",
    "graphite",
    "ink",
    "ivory",
    "latex",
    "leather",
    "marble",
    "metal",
    "metalwork",
    "mixed media",
    "mosaic",
    "oil on canvas",
    "paper",
    "pastel",
    "pastels",
    "plaster",
    "plastic",
    "porcelain",
    "resin",
    "sand",
    "sculpture",
    "silicone",
    "silkscreen",
    "steel",
    "stone",
    "stone carving",
    "terra cotta",
    "textile",
    "textiles",
    "watercolor",
    "wax",
    "wood",
    "woodcut",
]

perspectives = [
    "abstracted",
    "aerial",
    "anamorphic",
    "bird's eye",
    "cinematic",
    "close-up",
    "curvilinear",
    "deep",
    "depth of field",
    "distorted",
    "dutch angle",
    "elevated",
    "eye-level",
    "first-person",
    "fish-eye",
    "five-point",
    "flat",
    "four-point",
    "fragmented",
    "frontal",
    "harmonized",
    "high angle",
    "integrated",
    "isometric",
    "linear",
    "low angle",
    "macro",
    "maximalist",
    "micro",
    "minimalist",
    "naturalistic",
    "oblique",
    "orthographic",
    "over-the-shoulder",
    "panoramic",
    "rack focus",
    "selective focus",
    "single-point",
    "stylized",
    "telephoto",
    "third-person",
    "three-point",
    "tilted",
    "two-point",
    "wide angle",
    "worm's eye",
]

rendering_styles = [
    "abstract",
    "airbrush",
    "ascii art",
    "batik",
    "cartoon",
    "cel-shaded",
    "chalk",
    "charcoal",
    "collage",
    "comic book style",
    "contour drawing",
    "crosshatch",
    "cubist",
    "decoupage",
    "digital 3d",
    "embossing",
    "engraving",
    "etching",
    "expressionist",
    "fractal art",
    "fresco",
    "giclée",
    "gouache",
    "graffiti",
    "hyperrealistic",
    "iconography",
    "illumination",
    "impressionist",
    "isometric",
    "line art",
    "linocut",
    "lithography",
    "low-poly",
    "miniature",
    "minimalist",
    "monoprint",
    "mosaic",
    "oil painting",
    "orthographic",
    "papercut",
    "pastel",
    "photorealistic",
    "pixel art",
    "pixelated",
    "pointillist",
    "pyrography",
    "quilling",
    "relief",
    "retro",
    "silhouette",
    "silkscreen",
    "sketch",
    "stained glass",
    "stippling",
    "stylized",
    "surrealist",
    "tapestry",
    "vector",
    "vintage",
    "voxel",
    "watercolor",
    "wireframe",
    "woodcut",
]

subjects = [
    "a beach",
    "a bird",
    "a celestial body",
    "a cityscape",
    "a cultural monument",
    "a famous landmark",
    "a famous painting",
    "a festival",
    "a forest",
    "an historical figure",
    "a mountain",
    "a mythological creature",
    "a person",
    "a river",
    "a room interior",
    "a rural landscape",
    "a skyscraper",
    # "a still life",
    "a sunset",
    "a vehicle",
    "abstract shape",
    # "an abstract concept",
    "an animal",
    "an instrument",
    "an urban skyline",
    "animal",
    "beach",
    "book",
    "bridge",
    "castle",
    "cave",
    "clothing",
    "cloud",
    "computer",
    "farm",
    "flower",
    "food",
    "forest",
    "fruit",
    "furniture",
    "galaxy",
    "garden",
    "germ",
    "glacier",
    # "glimpse",
    "glove",
    "glow",
    "goal",
    "goddess",
    "gold",
    # "golf",
    # "gospel",
    # "gossip",
    # "gourmet",
    # "grace",
    "grape",
    "grass",
    # "gravity",
    "guitar",
    "gum",
    # "guru",
    # "habit",
    "hail",
    "haircut",
    # "half",
    "hallway",
    "ham",
    # "happiness",
    "harbor",
    # "harvest",
    "hat",
    # "hatred",
    # "health",
    "helmet",
    "herb",
    # "hero",
    # "highlight",
    "hill",
    # "hint",
    "historical figure",
    "hockey",
    # "homework",
    "honey",
    # "horror",
    "horse",
    # "hospitality",
    # "host",
    # "humidity",
    # "hunger",
    # "hunt",
    # "hurdle",
    "hurricane",
    "iceberg",
    # "icon",
    # "idea",
    # "idiom",
    # "ignorance",
    # "illusion",
    # "image",
    # "indicator",
    # "individual",
    # "information",
    # "ink",
    # "inquiry",
    "insect",
    # "insight",
    "instrument",
    # "interference",
    # "internet",
    # "interview",
    # "introduction",
    # "invention",
    # "investment",
    # "irony",
    "island",
    # "item",
    # "ivory",
    "jacket",
    "jam",
    # "jazz",
    # "jealousy",
    "jewel",
    # "job",
    # "joke",
    # "journal",
    # "journey",
    # "joy",
    # "judge",
    # "juice",
    # "jump",
    "jungle",
    # "justice",
    # "keen",
    "key",
    # "kindness",
    # "kingdom",
    "kiss",
    # "knowledge",
    "lab",
    # "labor",
    "ladder",
    "lake",
    "lamb",
    "lamp",
    "landscape",
    # "language",
    "laptop",
    # "laugh",
    # "laughter",
    "lawyer",
    # "leader",
    # "legacy",
    # "legend",
    # "lesson",
    "letter",
    # "liberty",
    "library",
    "license",
    # "lifestyle",
    "lightning",
    "lion",
    "lips",
    "liquid",
    # "literature",
    "lobby",
    # "location",
    # "loneliness",
    # "lottery",
    # "love",
    # "loyalty",
    "luggage",
    "machine",
    # "madness",
    "magazine",
    # "magic",
    "mailbox",
    # "mainstream",
    # "majority",
    # "makeup",
    "mall",
    # "management",
    "mango",
    # "manner",
    # "manuscript",
    "map",
    # "marathon",
    # "march",
    # "margin",
    "marker",
    # "market",
    # "maturity",
    "maze",
    # "meal",
    # "meaning",
    # "mechanism",
    "medicine",
    # "medium",
    # "meme",
    # "memory",
    # "menu",
    # "mercy",
    # "merit",
    # "message",
    # "metal",
    # "method",
    "microscope",
    # "mile",
    "milk",
    # "millennium",
    # "mindset",
    # "mineral",
    # "miracle",
    # "mischief",
    # "misery",
    # "mission",
    # "mistake",
    # "mix",
    # "model",
    # "momentum",
    "money",
    "moon",
    # "morality",
    # "mortgage",
    "mountain",
    # "mystery",
    # "myth",
    # "narrative",
    "nation",
    # "nature",
    # "necessity",
    # "network",
    # "news",
    # "nightmare",
    # "nobility",
    # "nonsense",
    # "normal",
    # "novel",
    # "nuance",
    # "nucleus",
    # "obstacle",
    # "occasion",
    "ocean",
    # "offense",
    "oil",
    # "opinion",
    # "opportunity",
    # "option",
    # "order",
    # "origin",
    # "outcome",
    # "outline",
    # "outlook",
    # "output",
    # "oxygen",
    "oyster",
    # "pace",
    # "pain",
    # "painting",
    # "palace",
    "palm",
    # "panel",
    # "panic",
    # "paradigm",
    # "paragraph",
    # "parallel",
    # "parameter",
    # "parent",
    "park",
    # "participation",
    # "passage",
    # "passion",
    # "patent",
    "path",
    # "patience",
    # "pattern",
    # "payment",
    # "peace",
    # "peak",
    "pen",
    # "penalty",
    # "pension",
    # "people",
    # "pepper",
    # "percentage",
    # "perception",
    # "performance",
    # "period",
    # "permission",
    "person",
    # "personality",
    # "perspective",
    "pet",
    # "phenomenon",
    # "philosophy",
    "phone",
    "photo",
    # "physics",
    "piano",
    "picture",
    # "piece",
    # "place",
    "planet",
    # "planning",
    "platform",
    # "play",
    # "pleasure",
    # "plot",
    "pocket",
    "poem",
    # "poet",
    # "point",
    # "policy",
    # "politics",
    # "poll",
    # "pollution",
    # "population",
    # "portfolio",
    # "position",
    # "possibility",
    # "posture",
    "potato",
    # "potential",
    # "practice",
    "prairie",
    # "pride",
    # "profile",
    # "profit",
    # "progress",
    # "project",
    # "promise",
    # "prospect",
    # "protocol",
    # "provider",
    # "province",
    # "psychology",
    # "publicity",
    # "pulse",
    # "purpose",
    # "quality",
    # "quantity",
    # "quarter",
    # "question",
    # "queue",
    # "quote",
    # "race",
    # "radiation",
    # "ratio",
    # "rational",
    # "reality",
    # "reason",
    # "recession",
    # "recipe",
    # "recognition",
    "record",
    "reef",
    # "religion",
    # "reputation",
    # "requirement",
    # "research",
    # "residence",
    # "resistance",
    # "resolution",
    # "resource",
    # "respect",
    # "response",
    # "responsibility",
    # "rest",
    # "result",
    # "retail",
    # "retirement",
    # "return",
    # "revenue",
    # "review",
    # "revolution",
    # "rhythm",
    "rice",
    # "rich",
    # "ride",
    # "right",
    # "risk",
    "river",
    "road",
    # "role",
    "room",
    # "routine",
    "ruler",
    # "safety",
    # "salary",
    # "sample",
    # "sanction",
    # "satisfaction",
    "scale",
    # "scenario",
    # "scene",
    # "schedule",
    # "scheme",
    # "science",
    # "scope",
    # "score",
    "screen",
    "script",
    # "sculpture",
    # "search",
    # "season",
    "seat",
    # "second",
    # "section",
    # "sector",
    # "security",
    # "segment",
    # "selection",
    # "self",
    # "seller",
    # "senior",
    # "sense",
    # "sentence",
    # "series",
    # "service",
    # "session",
    # "set",
    # "setting",
    # "share",
    "sheep",
    "shelf",
    "ship",
    # "shock",
    "shoe",
    "shop",
    # "short",
    # "shot",
    "shoulder",
    # "show",
    # "side",
    "sign",
    "signal",
    "signature",
    # "significance",
    # "silence",
    # "silver",
    # "similarity",
    # "simple",
    # "single",
    # "site",
    # "situation",
    # "size",
    # "skill",
    # "skin",
    "sky",
    "skyscraper",
    # "sleep",
    # "slice",
    "slide",
    # "slope",
    "smile",
    "snow",
    "soil",
    # "space",
    "speaker",
    # "spirit",
    # "sport",
    # "spot",
    # "spread",
    "spring",
    "coiled spring"
    "square",
    # "stability",
    "staff",
    "stage",
    "stalk",
    # "stand",
    # "standard",
    "star",
    # "start",
    "state",
    # "statement",
    # "status",
    "step",
    "stick",
    # "still",
    # "stock",
    "stone",
    # "stop",
    "store",
    # "story",
    # "strategy",
    "street",
    # "strength",
    "structure",
    "student",
    # "studio",
    # "study",
    # "stuff",
    # "style",
    # "subject",
    # "success",
    "sugar",
    # "suggestion",
    "suit",
    "summer",
    "sun",
    "sunset",
    # "supermarket",
    # "supply",
    # "support",
    "surface",
    # "surprise",
    # "survey",
    # "system",
    "table",
    "tablet",
    # "tale",
    # "talk",
    "cassette tape",
    "target",
    # "task",
    # "taste",
    # "tax",
    # "team",
    # "technology",
    "television",
    # "temperature",
    # "tendency",
    # "term",
    # "test",
    "text",
    "the ocean",
    # "theme",
    # "theory",
    # "thing",
    # "thought",
    # "threat",
    "ticket",
    # "time",
    # "timing",
    # "tip",
    "tissue",
    # "title",
    "tool",
    # "top",
    # "topic",
    # "total",
    # "touch",
    # "tour",
    # "tournament",
    "track",
    # "trade",
    # "tradition",
    # "traffic",
    "trail",
    # "transaction",
    # "transition",
    "transport",
    # "travel",
    # "treat",
    # "treatment",
    "tree",
    # "trial",
    # "trip",
    # "trouble",
    "truck",
    # "trust",
    # "truth",
    # "try",
    # "tune",
    # "turn",
    # "type",
    # "unit",
    "universe",
    "university",
    # "update",
    # "upgrade",
    "urban skyline",
    # "user",
    # "utility",
    "valley",
    # "value",
    # "variety",
    "vehicle",
    # "version",
    # "video",
    # "view",
    "village",
    # "violation",
    # "virtue",
    # "vision",
    # "visit",
    # "visual",
    # "voice",
    # "volume",
    # "vote",
    # "wage",
    # "wait",
    # "walk",
    "wall",
    # "war",
    "watch",
    "water",
    "waterfall",
    "wave",
    "weapon",
    # "weather",
    "web",
    # "weight",
    "well",
    "wheel",
]

textures = [
    "braided",
    "brittle",
    "ceramic",
    "corrugated",
    "crystalline",
    "dense",
    "dry",
    "elastic",
    "feathery",
    "fibrous",
    "flexible",
    "fluffy",
    "frayed",
    "furry",
    "glassy",
    "glossy",
    "gritty",
    "hard",
    "hollow",
    "jagged",
    "knitted",
    "leathery",
    "matte",
    "meshed",
    "metallic",
    "opaque",
    "pebbled",
    "plastic",
    "porous",
    "rigid",
    "rough",
    "rubbery",
    "sandy",
    "scaly",
    "silky",
    "slippery",
    "smooth",
    "soft",
    "solid",
    "spiky",
    "spongy",
    "sticky",
    "translucent",
    "transparent",
    "velvety",
    "wet",
    "woody",
    "woven",
]

time_of_day = [
    "astronomical twilight",
    "bedtime",
    "blue hour",
    "civil twilight",
    "dawn",
    "daybreak",
    "dinner time",
    "dusk",
    "early afternoon",
    "early evening",
    "early morning",
    "evening rush",
    "first light",
    "golden hour",
    "high noon",
    "last light",
    "late afternoon",
    "late evening",
    "late morning",
    "lunchtime",
    "mid-afternoon",
    "mid-evening",
    "mid-morning",
    "midday",
    "midnight",
    "moonrise",
    "moonset",
    "morning rush",
    "nautical twilight",
    "night",
    "post-dusk",
    "post-sunrise",
    "pre-dawn",
    "pre-sunset",
    "siesta",
    "sun nadir",
    "sun zenith",
    "sunrise",
    "sunset",
    "teatime",
    "twilight",
    "waking moment",
    "witching hour",
]

weather_conditions = [
    "arid",
    "balmy",
    "blazing",
    "blizzard",
    "chilly",
    "clear",
    "cloudy",
    "cold",
    "cold snap",
    "crisp",
    "cyclonic",
    "damp",
    "dew",
    "drizzle",
    "dry",
    "dusty",
    "fogbank",
    "foggy",
    "freezing",
    "frigid",
    "frost",
    "gusty",
    "hail",
    "heatwave",
    "heavy wind",
    "hot",
    "humid",
    "ice storm",
    "light breeze",
    "mild",
    "misty",
    "monsoonal",
    "oppressive",
    "overcast",
    "polluted",
    "rainy",
    "refreshing",
    "sandstorm",
    "shower",
    "sleet",
    "smoggy",
    "snowy",
    "still",
    "stormy",
    "sunny",
    "thunderstorm",
    "torrential",
    "tropical",
    "windy",
]
