artistic_styles = [
    "abstract",
    "art deco",
    "art nouveau",
    "automatism",
    "baroque",
    "classical",
    "cloisonnism",
    "constructivist",
    "contemporary",
    "cubist",
    "dada",
    "divisionism",
    "expressionist",
    "fauvist",
    "futurist",
    "geometric",
    "gothic",
    "graffiti",
    "hyperrealism",
    "impressionist",
    "lyric abstraction",
    "mannerism",
    "metaphysical",
    "minimalist",
    "naive",
    "naturalism",
    "neo-expressionism",
    "neo-impressionism",
    "neoclassical",
    "neoplasticism",
    # "op art",
    "orphism",
    "photomontage",
    "photorealistic",
    "pixel art",
    "pointillist",
    "pop art",
    "pop",
    "post-impressionism",
    "precisionism",
    "primitivism",
    "realist",
    "renaissance",
    "rococo",
    "romantic",
    "spectralism",
    "stippling",
    "street art",
    "stuckist",
    "suprematist",
    "surrealist",
    "symbolist",
    "tachisme",
    "transgressive",
]

color_palettes = [
    "achromatic",
    "analogous colors",
    "analogous",
    "black and white",
    "clash",
    "complementary colors",
    "complementary",
    "cool tones",
    "dark",
    "desaturated",
    "discordant",
    "duotone",
    "earth tones",
    "fauvist",
    "grayscale",
    "harmonious",
    "high contrast",
    "light",
    "low contrast",
    "matte",
    "metallic",
    "monochromatic",
    "monochrome",
    "multicolor",
    "muted",
    "natural",
    "neon",
    "neutral",
    "pastel",
    "polychromatic",
    "primary colors",
    "psychedelic",
    "rectangular",
    "retro",
    "saturated",
    "secondary colors",
    "sepia",
    "shaded",
    "solarized",
    "split-complementary",
    "square",
    "synthetic",
    "tertiary colors",
    "tetradic colors",
    "tetradic",
    "tinted",
    "toned",
    "triadic colors",
    "triadic",
    "vibrant",
    "vintage",
    "warm tones",
]

emotions = [
    "ambitious",
    "amused",
    "angry",
    "anxious",
    "apathetic",
    "assertive",
    "awkward",
    "bewildered",
    "bored",
    "brave",
    "calm",
    "comfortable",
    "compassionate",
    "confident",
    "content",
    "curious",
    "discontent",
    "distracted",
    "eager",
    "ecstatic",
    "energetic",
    "enthusiastic",
    "envious",
    "excited",
    "fearful",
    "focused",
    "forlorn",
    "grateful",
    "hateful",
    "hesitant",
    "hopeful",
    "indifferent",
    "insecure",
    "introspective",
    "joyful",
    "lazy",
    "loving",
    "melancholic",
    "mysterious",
    "optimistic",
    "peaceful",
    "pensive",
    "pessimistic",
    "reluctant",
    "secure",
    "serene",
    "timid",
]

geographical_locations = [
    "archipelago",
    "arctic",
    "canyon",
    "cave",
    "cliff",
    "coastal",
    "coral reef",
    "delta",
    "desert",
    "dune",
    "estuary",
    "farmland",
    "fjord",
    "forest",
    "garden",
    "glacier",
    "grove",
    "hill",
    "island",
    "jungle",
    "lagoon",
    "lakeside",
    "marshland",
    "meadow",
    "mountainous",
    "oceanic",
    "orchard",
    "plain",
    "plateau",
    "pond",
    "prairie",
    "ridge",
    "riverine",
    "rural",
    "savanna",
    "steppe",
    "suburban",
    "swamp",
    "taiga",
    "tropical",
    "tundra",
    "urban",
    "valley",
    "vineyard",
    "volcanic",
    "waterfall",
]

historical_references = [
    "agricultural",
    "ancient",
    "atomic age",
    # "aztec",
    "babylonian",
    "baroque",
    "bronze age",
    "byzantine",
    # "civil war",
    # "cold war",
    "colonial",
    "dark ages",
    "democratic",
    "egyptian",
    "enlightenment",
    "feudal",
    # "gothic",
    # "han dynasty",
    "hellenistic",
    "hunter-gatherer",
    "imperial",
    "incan",
    "industrial",
    "information age",
    "iron age",
    # "islamic golden age",
    # "mayan",
    "medieval",
    "modern",
    # "mughal",
    "neolithic",
    "oligarchy",
    # "ottoman",
    # "persian",
    "prehistoric",
    "renaissance",
    "republic",
    "roaring twenties",
    "roman",
    "space age",
    "sumerian",
    "theocracy",
    "tribal",
    "victorian",
    "viking",
    # "world war i",
    # "world war ii",
]

interactions = [
    "aligning",
    "amplifying",
    "balancing",
    "clashing",
    "coalescing",
    "complementing",
    "contrasting",
    "dampening",
    "diminishing",
    "disordering",
    "disrupting",
    "distorting",
    "diverging",
    "dominating",
    "encircling",
    "enhancing",
    "following",
    "fragmenting",
    "freeing",
    "fusing",
    "guiding",
    "halting",
    "highlighting",
    "illuminating",
    "inspiring",
    "interrupting",
    "intersecting",
    "merging",
    "mimicking",
    "misleading",
    "muting",
    "obscuring",
    "organizing",
    "overlapping",
    "paralleling",
    "pausing",
    "polarizing",
    "preceding",
    "reflecting",
    "revealing",
    "rushing",
    "separating",
    "shadowing",
    "submitting",
    "supporting",
    "trapping",
    "unbalancing",
    "uniting",
]

mediums = [
    "acrylic",
    "aluminum",
    "bronze",
    "ceramic",
    "chalk",
    "charcoal",
    "clay",
    "collage",
    "concrete",
    "copper",
    "coral",
    "crystal",
    "digital art",
    "enamel",
    "etching",
    "fabric",
    "fiberglass",
    "fur",
    "glass",
    "gold leaf",
    "gouache",
    "granite",
    "graphite",
    "ink",
    "ivory",
    "latex",
    "leather",
    "marble",
    "metal",
    "metalwork",
    "mixed media",
    "mosaic",
    "oil on canvas",
    "paper",
    "pastel",
    "pastels",
    "plaster",
    "plastic",
    "porcelain",
    "resin",
    "sand",
    "sculpture",
    "silicone",
    "silkscreen",
    "steel",
    "stone carving",
    "stone",
    "terra cotta",
    "textile",
    "textiles",
    "watercolor",
    "wax",
    "wood",
    "woodcut",
]

perspectives = [
    "abstracted",
    "aerial",
    "anamorphic",
    "bird's eye",
    "cinematic",
    "close-up",
    "curvilinear",
    "deep",
    "depth of field",
    "distorted",
    "dutch angle",
    "elevated",
    "eye-level",
    "first-person",
    "fish-eye",
    "five-point",
    "flat",
    "four-point",
    "fragmented",
    "frontal",
    "harmonized",
    "high angle",
    "integrated",
    "isometric",
    "linear",
    "low angle",
    "macro",
    "maximalist",
    "micro",
    "minimalist",
    "naturalistic",
    "oblique",
    "orthographic",
    "over-the-shoulder",
    "panoramic",
    "rack focus",
    "selective focus",
    "single-point",
    "stylized",
    "telephoto",
    "third-person",
    "three-point",
    "tilted",
    "two-point",
    "wide angle",
    "worm's eye",
]

rendering_styles = [
    "abstract",
    "airbrush",
    "ascii art",
    "batik",
    "cartoon",
    "cel-shaded",
    "chalk",
    "charcoal",
    "collage",
    "comic book style",
    "contour drawing",
    "crosshatch",
    "cubist",
    "decoupage",
    "digital 3d",
    "embossing",
    "engraving",
    "etching",
    "expressionist",
    "fractal art",
    "fresco",
    "giclée",
    "gouache",
    "graffiti",
    "hyperrealistic",
    "iconography",
    "illumination",
    "impressionist",
    "isometric",
    "line art",
    "linocut",
    "lithography",
    "low-poly",
    "miniature",
    "minimalist",
    "monoprint",
    "mosaic",
    "oil painting",
    "orthographic",
    "papercut",
    "pastel",
    "photorealistic",
    "pixel art",
    "pixelated",
    "pointillist",
    "pyrography",
    "quilling",
    "relief",
    "retro",
    "silhouette",
    "silkscreen",
    "sketch",
    "stained glass",
    "stippling",
    "stylized",
    "surrealist",
    "tapestry",
    "vector",
    "vintage",
    "voxel",
    "watercolor",
    "wireframe",
    "woodcut",
]

subjects = [
    "a beach",
    "a bird",
    "a celestial body",
    "a cityscape",
    "a cultural monument",
    # "a still life",
    "abacus",
    "abstract shape",
    # "an abstract concept",
    "an agave planet",
    "an animal",
    "an historical figure",
    "an instrument",
    "an urban skyline",
    "animal",
    "armchair",
    "axe blade",
    "backpack",
    "baseball",
    "basket",
    "basketball net",
    "basketball",
    "battery meter icon",
    "battleship",
    "beach",
    "bean bag chair",
    "beer can",
    "beer tap handle",
    "binder",
    "bishop",
    "bluetooth icon",
    "book",
    "book",
    "bookshelf",
    "bourbon bottle",
    "bowl",
    "bowling pin",
    "bowstring bridge",
    "brandy snifter",
    "bridge",
    "broken links icon",
    "calculator",
    "calendar",
    "cassette tape",
    "cast iron pan",
    "castle",
    "cave",
    "chair",
    "champagne flute",
    "chicken",
    "clock",
    "clothing",
    "cloud",
    "coat of arms",
    "coiled spring" "comb",
    "compass",
    "computer memory",
    "computer",
    "computer",
    "condiment bottle",
    "conditioner",
    "corkboard",
    "crenellation",
    "crown",
    "cup",
    "cushion",
    "desk calendar",
    "desk chair",
    "desk lamp",
    "desk organizer",
    "desk tray",
    "desk",
    "dish",
    "dress",
    "embrasure",
    "eraser",
    "ethernet icon",
    "ethernet symbol",
    "eyeglasses",
    "family crest",
    "famous landmark",
    "famous painting",
    "farm",
    "festival",
    "file cabinet",
    "floating lantern",
    "flower",
    "food",
    "football",
    "forest",
    "forest",
    "fork",
    "fruit",
    "furniture",
    "galaxy",
    "garden",
    "geode",
    "geometric compass",
    "germ",
    "glacier",
    # "glimpse",
    "glove",
    "gloves",
    "glow",
    "glue",
    "goal",
    "goddess",
    "gold",
    # "golf",
    # "gospel",
    # "gossip",
    # "gourmet",
    # "grace",
    "graduation gown",
    "grape",
    "grass",
    # "gravity",
    "guitar",
    "gum",
    # "guru",
    # "habit",
    "hail",
    "hairbrush",
    "haircut",
    # "half",
    "hallway",
    "ham",
    "hammer",
    # "happiness",
    "harbor",
    "hard drive symbol",
    "harp",
    # "harvest",
    "hat",
    "hat",
    # "hatred",
    "headphones",
    # "health",
    "helmet",
    "herb",
    # "hero",
    "heterochromia iridum",
    # "highlight",
    "highlighter",
    "hill",
    # "hint",
    "historical figure",
    "hockey puck",
    # "hockey",
    "hole puncher",
    # "homework",
    "honey",
    # "horror",
    "horse",
    "horseshoe",
    # "hospitality",
    # "host",
    # "humidity",
    # "hunger",
    # "hunt",
    # "hurdle",
    "hurricane",
    "iceberg",
    # "icon",
    # "idea",
    # "idiom",
    # "ignorance",
    # "illusion",
    # "image",
    # "indicator",
    # "individual",
    # "information",
    # "ink",
    # "inquiry",
    "insect",
    # "insight",
    "instrument",
    # "interference",
    "interlaced initials",
    # "internet",
    # "interview",
    # "introduction",
    # "invention",
    # "investment",
    # "irony",
    "island",
    # "item",
    # "ivory",
    "jackalope",
    "jacket",
    "jacket",
    "jackrabbit",
    "jam",
    # "jazz",
    # "jealousy",
    "jewel",
    # "job",
    # "joke",
    # "journal",
    # "journey",
    # "joy",
    # "judge",
    # "juice",
    # "jump",
    "jungle",
    # "justice",
    # "keen",
    "key",
    "keyboard",
    "keychain",
    # "kindness",
    # "kingdom",
    "kiss",
    "knife",
    "knight",
    # "knowledge",
    "lab",
    "label maker",
    # "labor",
    "ladder",
    "lake",
    "lamb",
    "lamp",
    "lamp",
    "landscape",
    # "language",
    "laptop",
    "lattice bridge",
    # "laugh",
    # "laughter",
    "lawyer",
    # "leader",
    # "legacy",
    # "legend",
    # "lesson",
    "letter",
    # "liberty",
    "library",
    "license",
    # "lifestyle",
    "lightning",
    "links icon",
    "lion",
    "lips",
    "liquid",
    # "literature",
    "lobby",
    "location icon",
    # "location",
    "log cabin",
    # "loneliness",
    # "lottery",
    # "love",
    # "loyalty",
    "luggage",
    "machine",
    # "madness",
    "magazine",
    # "magic",
    "mailbox",
    # "mainstream",
    # "majority",
    # "makeup",
    "mall",
    # "management",
    "mango",
    # "manner",
    # "manuscript",
    "map",
    # "marathon",
    # "march",
    # "margin",
    "marker",
    "marker",
    # "market",
    # "maturity",
    "maze",
    # "meal",
    # "meaning",
    "mechanical watch",
    # "mechanism",
    "medicine",
    # "medium",
    # "meme",
    # "memory",
    # "menu",
    # "mercy",
    # "merit",
    # "message",
    # "metal",
    # "method",
    "microphone",
    "microscope",
    # "mile",
    "milk",
    # "millennium",
    # "mindset",
    # "mineral",
    # "miracle",
    "mirror",
    # "mischief",
    # "misery",
    # "mission",
    # "mistake",
    # "mix",
    # "model",
    # "momentum",
    "money",
    "monitor",
    "moon",
    # "morality",
    # "mortgage",
    "mountain",
    "mouse",
    "mug",
    # "mystery",
    # "myth",
    "mythological creature",
    # "narrative",
    "nation",
    # "nature",
    # "necessity",
    # "network",
    # "news",
    "newspaper",
    # "nightmare",
    # "nobility",
    # "nonsense",
    # "normal",
    "notebook",
    "notebook",
    # "novel",
    # "nuance",
    # "nucleus",
    # "obstacle",
    # "occasion",
    "ocean",
    # "offense",
    "office supplies",
    "oil",
    # "opinion",
    # "opportunity",
    # "option",
    # "order",
    # "origin",
    "ottoman",
    # "outcome",
    # "outline",
    # "outlook",
    # "output",
    # "oxygen",
    "oyster",
    # "pace",
    # "pain",
    # "painting",
    # "palace",
    "palm",
    # "panel",
    # "panic",
    "pants",
    "paper clips",
    "paper lantern",
    "paper shredder",
    "paper",
    # "paradigm",
    # "paragraph",
    # "parallel",
    # "parameter",
    "parasol",
    # "parent",
    "park",
    # "participation",
    # "passage",
    # "passion",
    # "patent",
    "path",
    # "patience",
    # "pattern",
    "pawn",
    # "payment",
    # "peace",
    # "peak",
    "pen",
    "pen",
    # "penalty",
    "pencil holder",
    "pencil sharpener",
    "pencil",
    # "pension",
    # "people",
    # "pepper",
    # "percentage",
    # "perception",
    # "performance",
    # "period",
    # "permission",
    "person",
    "person",
    # "personality",
    # "perspective",
    "pet",
    # "phenomenon",
    # "philosophy",
    "phone",
    "phone",
    "photo",
    # "physics",
    "piano keys",
    "piano",
    "pickleball",
    "picnic basket",
    "picture",
    # "piece",
    "pint glass",
    "pitcher",
    # "place",
    "planet",
    # "planning",
    "plate",
    "platform",
    # "play",
    # "pleasure",
    # "plot",
    "pocket",
    "poem",
    # "poet",
    # "point",
    # "policy",
    # "politics",
    # "poll",
    # "pollution",
    "pop filter",
    # "population",
    # "portfolio",
    # "position",
    # "possibility",
    # "posture",
    "potato",
    # "potential",
    "power symbol",
    # "practice",
    "prairie",
    # "pride",
    "printer",
    # "profile",
    # "profit",
    # "progress",
    # "project",
    # "promise",
    # "prospect",
    # "protocol",
    "protractor",
    # "provider",
    # "province",
    # "psychology",
    # "publicity",
    # "pulse",
    # "purpose",
    "push pins",
    # "quality",
    # "quantity",
    # "quarter",
    # "question",
    # "queue",
    # "quote",
    # "race",
    # "radiation",
    # "ratio",
    # "rational",
    "razor",
    "reading lamp",
    # "reality",
    # "reason",
    # "recession",
    # "recipe",
    # "recognition",
    "record",
    "rectangular paper lantern",
    "recycle icon",
    "recycle symbol",
    "recycling bin",
    "reef",
    "refresh symbol",
    # "religion",
    # "reputation",
    # "requirement",
    # "research",
    # "residence",
    # "resistance",
    # "resolution",
    # "resource",
    # "respect",
    # "response",
    # "responsibility",
    # "rest",
    # "result",
    # "retail",
    # "retirement",
    # "return",
    # "revenue",
    # "review",
    # "revolution",
    # "rhythm",
    "rice",
    # "rich",
    # "ride",
    # "right",
    # "risk",
    "river",
    "river",
    "road",
    # "role",
    "roof truss",
    "rook",
    "room interior",
    "room",
    # "routine",
    "rubber bands",
    "rubix cube",
    "ruler",
    "rural landscape",
    # "safety",
    # "salary",
    # "sample",
    # "sanction",
    # "satisfaction",
    "saucer",
    "scale",
    "scanner",
    "scarf",
    # "scenario",
    # "scene",
    # "schedule",
    # "scheme",
    # "science",
    "scissors",
    # "scope",
    # "score",
    "screen",
    "script",
    # "sculpture",
    # "search",
    # "season",
    "seat",
    # "second",
    # "section",
    # "sector",
    # "security",
    # "segment",
    # "selection",
    # "self",
    # "seller",
    # "senior",
    # "sense",
    # "sentence",
    # "series",
    # "service",
    # "session",
    # "set",
    # "setting",
    "shampoo",
    # "share",
    "sheep",
    "shelf",
    "ship",
    # "shock",
    "shoe",
    "shoes",
    "shop",
    # "short",
    # "shot",
    "shoulder",
    # "show",
    # "side",
    "sign",
    "signal",
    "signature",
    # "significance",
    # "silence",
    # "silver",
    # "similarity",
    # "simple",
    # "single",
    # "site",
    # "situation",
    # "size",
    # "skill",
    # "skin",
    "sky",
    "skyscraper",
    "skyscraper",
    # "sleep",
    # "slice",
    "slide",
    # "slope",
    "smile",
    "snow",
    "soap",
    "socks",
    "soil",
    # "space",
    "speaker",
    # "spirit",
    "sponge",
    "spoon",
    # "sport",
    # "spot",
    # "spread",
    "spring",
    "square paper pantern",
    "square",
    # "stability",
    "staff",
    "stage",
    "stained glass window",
    "stalk",
    # "stand",
    # "standard",
    "stapler",
    "star",
    # "start",
    "state",
    # "statement",
    # "status",
    "step",
    "stick",
    "sticky notes",
    # "still",
    # "stock",
    "stone",
    "stool",
    # "stop",
    "store",
    # "story",
    # "strategy",
    "street",
    # "strength",
    "structure",
    "student",
    # "studio",
    # "study",
    # "stuff",
    # "style",
    # "subject",
    # "success",
    "sugar",
    # "suggestion",
    "suit",
    "summer",
    "sun",
    "sunglasses",
    "sunset",
    "sunset",
    # "supermarket",
    # "supply",
    # "support",
    "surface",
    # "surprise",
    # "survey",
    # "system",
    "t-shirt",
    "table",
    "table",
    "tablet",
    # "tale",
    # "talk",
    "tape",
    "target",
    # "task",
    # "taste",
    # "tax",
    # "team",
    # "technology",
    "television",
    # "temperature",
    # "tendency",
    "tennis ball",
    # "term",
    # "test",
    "text",
    "the ocean",
    # "theme",
    # "theory",
    # "thing",
    # "thought",
    # "threat",
    "thumbtacks",
    "tiara",
    "ticket",
    # "time",
    # "timing",
    # "tip",
    "tissue",
    # "title",
    "tombstone",
    "tool",
    "toothbrush",
    "toothpaste",
    # "top",
    # "topic",
    # "total",
    # "touch",
    # "tour",
    # "tournament",
    "towel",
    "track",
    # "trade",
    # "tradition",
    # "traffic",
    "trail",
    # "transaction",
    # "transition",
    "transport",
    "trash can",
    # "travel",
    # "treat",
    # "treatment",
    "tree",
    # "trial",
    "triangle with rounded corners",
    "triangle",
    # "trip",
    "trophy",
    # "trouble",
    "truck",
    "trumpet",
    # "trust",
    # "truth",
    # "try",
    # "tune",
    "tuning fork",
    # "turn",
    "turret",
    # "type",
    "umbrella",
    "umbrella",
    # "unit",
    "universe",
    "university",
    # "update",
    # "upgrade",
    "urban skyline",
    "usb icon",
    # "user",
    "utensil",
    # "utility",
    "valley",
    # "value",
    # "variety",
    "vehicle",
    # "version",
    # "video",
    # "view",
    "village",
    "vintage phone box",
    # "violation",
    # "virtue",
    # "vision",
    # "visit",
    # "visual",
    # "voice",
    "volume icon",
    # "volume",
    # "vote",
    # "wage",
    # "wait",
    # "walk",
    "wall",
    "wallet",
    # "war",
    "warren bridge",
    "wastebasket",
    "watch",
    "water bottle",
    "water",
    "waterfall",
    "wave",
    "weapon",
    # "weather",
    "web",
    # "weight",
    "well",
    "wheel",
    "whiskey glass",
    "whiteboard",
    "wifi icon",
    "wifi symbol",
    "windscreen",
    "wine bottle",
]

textures = [
    "braided",
    "brittle",
    "ceramic",
    "corrugated",
    "crystalline",
    "dense",
    "dry",
    "elastic",
    "feathery",
    "fibrous",
    "flexible",
    "fluffy",
    "frayed",
    "furry",
    "glassy",
    "glossy",
    "gritty",
    "hard",
    "hollow",
    "jagged",
    "knitted",
    "leathery",
    "matte",
    "meshed",
    "metallic",
    "opaque",
    "pebbled",
    "plastic",
    "porous",
    "rigid",
    "rough",
    "rubbery",
    "sandy",
    "scaly",
    "silky",
    "slippery",
    "smooth",
    "soft",
    "solid",
    "spiky",
    "spongy",
    "sticky",
    "translucent",
    "transparent",
    "velvety",
    "wet",
    "woody",
    "woven",
]

time_of_day = [
    "astronomical twilight",
    "bedtime",
    "blue hour",
    "civil twilight",
    "dawn",
    "daybreak",
    "dinner time",
    "dusk",
    "early afternoon",
    "early evening",
    "early morning",
    "evening rush",
    "first light",
    "golden hour",
    "high noon",
    "last light",
    "late afternoon",
    "late evening",
    "late morning",
    "lunchtime",
    "mid-afternoon",
    "mid-evening",
    "mid-morning",
    "midday",
    "midnight",
    "moonrise",
    "moonset",
    "morning rush",
    "nautical twilight",
    "night",
    "post-dusk",
    "post-sunrise",
    "pre-dawn",
    "pre-sunset",
    "siesta",
    "sun nadir",
    "sun zenith",
    "sunrise",
    "sunset",
    "teatime",
    "twilight",
    "waking moment",
    "witching hour",
]

weather_conditions = [
    "arid",
    "balmy",
    "blazing",
    "blizzard",
    "chilly",
    "clear",
    "cloudy",
    "cold snap",
    "cold",
    "crisp",
    "cyclonic",
    "damp",
    "dew",
    "drizzle",
    "dry",
    "dusty",
    "fogbank",
    "foggy",
    "freezing",
    "frigid",
    "frost",
    "gusty",
    "hail",
    "heatwave",
    "heavy wind",
    "hot",
    "humid",
    "ice storm",
    "light breeze",
    "mild",
    "misty",
    "monsoonal",
    "oppressive",
    "overcast",
    "polluted",
    "rainy",
    "refreshing",
    "sandstorm",
    "shower",
    "sleet",
    "smoggy",
    "snowy",
    "still",
    "stormy",
    "sunny",
    "thunderstorm",
    "torrential",
    "tropical",
    "windy",
]
